name: apex
on:
  workflow_dispatch:
  push:
    branches: [ "apex" ]
concurrency:
  group: "apex"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: alwaysdata-vic
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
         npm install --ci
         npm run build
      - run: |
         mkdir ~/.ssh
         echo "$SSH_KEY" > ~/.ssh/id_ed25519
         ssh-keyscan -t rsa ssh-vic.alwaysdata.net >> ~/.ssh/known_hosts
         chmod 400 ~/.ssh/*
         chmod 700 ~/.ssh
      - run: rsync -rz --mkpath dist/ vic@ssh-vic.alwaysdata.net:www/apex
      - run: rm -rf ~/.ssh

